version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - '3306:3306'
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - '3000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    expose:
      - '80'
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
